In [578]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

numpy -> olah numerik
pandas -> import external file

In [579]:
dataset = pd.read_csv('Ehe.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

: -> semua data
[baris, kolom]

In [580]:
print(x)

[['Indonesia' 27 72000]
 ['India' 29 48000]
 ['Russia' 30 54000]
 ['Slovakia' 32 61000]
 ['Togo' 31 45000]
 ['Spain' 25 50000]
 ['Toga' 28 52000]
 ['France' 28 79000]
 ['Russia' 42 83000]
 ['India' 35 67000]]


In [581]:
print(y)

['Yes' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No']


In [582]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [583]:
print(x)

[['Indonesia' 27.0 72000.0]
 ['India' 29.0 48000.0]
 ['Russia' 30.0 54000.0]
 ['Slovakia' 32.0 61000.0]
 ['Togo' 31.0 45000.0]
 ['Spain' 25.0 50000.0]
 ['Toga' 28.0 52000.0]
 ['France' 28.0 79000.0]
 ['Russia' 42.0 83000.0]
 ['India' 35.0 67000.0]]


In [584]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [585]:
print(x)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 27.0 72000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 29.0 48000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 32.0 61000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 31.0 45000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 25.0 50000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 28.0 52000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 28.0 79000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 42.0 83000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 35.0 67000.0]]


In [586]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [587]:
print(y)

[1 1 1 0 0 0 0 1 1 0]


In [588]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = 1)

In [589]:
print(x_train)

[[0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 35.0 67000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 28.0 52000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 31.0 45000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 27.0 72000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 32.0 61000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 29.0 48000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 28.0 79000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 42.0 83000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 25.0 50000.0]]


In [590]:
print(x_test)

[[0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 30.0 54000.0]]


In [591]:
print(y_train)

[0 0 0 1 0 1 1 1 0]


In [592]:
print(y_test)

[1]


In [593]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.fit_transform(x_test[:, 3:])

In [594]:
print(x_train)

[[0.0 1.0 0.0 -0.3535533905932738 -0.35355339059327373
  -0.3535533905932738 -0.3535533905932736 -0.35355339059327373
  0.8708635721768005 0.38515644241971186]
 [0.0 0.0 0.0 -0.3535533905932738 -0.35355339059327373
  -0.3535533905932738 2.828427124746189 -0.35355339059327373
  -0.5729365606426322 -0.7451939864207472]
 [0.0 0.0 0.0 -0.3535533905932738 -0.35355339059327373
  -0.3535533905932738 -0.3535533905932736 2.82842712474619
  0.0458349248514104 -1.2726908532129615]
 [0.0 0.0 1.0 -0.3535533905932738 -0.35355339059327373
  -0.3535533905932738 -0.3535533905932736 -0.35355339059327373
  -0.7791937224739798 0.7619399186998649]
 [0.0 0.0 0.0 -0.3535533905932738 2.82842712474619 -0.3535533905932738
  -0.3535533905932736 -0.35355339059327373 0.25209208668275795
  -0.06698372911647177]
 [0.0 1.0 0.0 -0.3535533905932738 -0.35355339059327373
  -0.3535533905932738 -0.3535533905932736 -0.35355339059327373
  -0.36667939881128464 -1.0466207674448695]
 [1.0 0.0 0.0 -0.3535533905932738 -0.35355339

In [595]:
print(x_test)

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]]
